### ISSUE TITLE
出现了奇怪的问题

### ISSUE THREAD

**Issue by return60** [layou233/ZBProxy#7]
> goroutine 862 [running]:
main.transfer({0x6b77e0, 0xc00000e010}, {0x6b77e0, 0xc00000e0f0}, 0x1000, 0x1)
        /home/runner/work/ZBProxy/ZBProxy/transfer.go:70 +0x815
created by main.forDial
        /home/runner/work/ZBProxy/ZBProxy/transfer.go:26 +0x231
这个问题非常常见

**Comment by return60** [comment]
个人使用，不定时出现问题
